/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}l=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=l;
function u(a,b){a.prototype=k(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.m=b.prototype}var x=this||self;function y(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length};var z=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function A(a){return Array.prototype.concat.apply([],arguments)};function B(a,b){this.g=b===C?a:""}B.prototype.i=!0;B.prototype.h=function(){return this.g.toString()};B.prototype.toString=function(){return this.g.toString()};var D=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,C={};function E(a,b){this.h={};this.g=[];this.i=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof E)for(c=a.l(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}g=E.prototype;g.j=function(){F(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};g.l=function(){F(this);return this.g.concat()};
function F(a){if(a.i!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];G(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.i!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],G(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}g.get=function(a,b){return G(this.h,a)?this.h[a]:b};g.set=function(a,b){G(this.h,a)||(this.i++,this.g.push(a));this.h[a]=b};g.forEach=function(a,b){for(var c=this.l(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
function G(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function H(a){if(a.j&&"function"==typeof a.j)return a.j();if("string"===typeof a)return a.split("");if(y(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};function I(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function J(){this.i=this.h=this.g=null}function K(a){a.g||(a.g=new E,a.h=0,a.i&&I(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}g=J.prototype;g.add=function(a,b){K(this);this.i=null;a=String(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function L(a,b){K(a);b=String(b);return G(a.g.h,b)}g.forEach=function(a,b){K(this);this.g.forEach(function(c,d){z(c,function(e){a.call(b,e,d,this)},this)},this)};
g.l=function(){K(this);for(var a=this.g.j(),b=this.g.l(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};g.j=function(a){K(this);var b=[];if("string"===typeof a)L(this,a)&&(b=A(b,this.g.get(String(a))));else{a=this.g.j();for(var c=0;c<a.length;c++)b=A(b,a[c])}return b};g.set=function(a,b){K(this);this.i=null;a=String(a);L(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};
g.get=function(a,b){if(!a)return b;a=this.j(a);return 0<a.length?String(a[0]):b};g.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=this.g.l(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.j(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.i=a.join("&")};function M(){}M.prototype.g=function(){};M.prototype.i=function(){};M.prototype.h=function(){};function O(){var a=x.__earth_integration;if(void 0===a)console.error("No Earth integration found.");else{var b=a?a.integration:void 0;switch(b){case a.WINDOW_OBJECT:a=new P;break;case a.URL_SCHEME:a=new Q;break;case a.IFRAME_CHANNEL:a=new R;break;case a.MESSAGE_HANDLER:a=new S;break;case void 0:a=new T;break;default:throw Error("Unknown Earth app integration strategy "+b+" found");}return a}}u(O,M);
function P(){}u(P,M);P.prototype.g=function(){x.earth.failedToLoadRichContent()};function R(){}u(R,M);R.prototype.g=function(){x.sendCommand_("failedToLoadRichContent",{})};function Q(){}u(Q,M);
Q.prototype.g=function(){var a={};if(a.l&&"function"==typeof a.l)var b=a.l();else if(a.j&&"function"==typeof a.j)b=void 0;else if(y(a)||"string"===typeof a){var c=[];b=a.length;for(var d=0;d<b;d++)c.push(d);b=c}else{c=[];b=0;for(d in a)c[b++]=d;b=c}if("undefined"==typeof b)throw Error("Keys are undefined");c=new J;a=H(a);for(d=0;d<b.length;d++){var e=b[d],f=a[d];if(Array.isArray(f)){var h=c,v=e;var m=v;K(h);m=String(m);G(h.g.h,m)&&(h.i=null,h.h-=h.g.get(m).length,e=h.g,G(e.h,m)&&(delete e.h[m],e.i--,
e.g.length>2*e.i&&F(e)));if(0<f.length){h.i=null;e=h.g;m=e.set;v=String(v);var r=f.length;if(0<r){for(var N=Array(r),w=0;w<r;w++)N[w]=f[w];r=N}else r=[];m.call(e,v,r);h.h+=f.length}}else c.add(e,f)}b=encodeURIComponent("failedToLoadRichContent");this.i(new B("comgoogleearthballoon:///"+b+"?"+c.toString(),C))};
Q.prototype.i=function(a){var b=document.createElement("a");a instanceof B||a instanceof B||(a="object"==typeof a&&a.i?a.h():String(a),D.test(a)||(a="about:invalid#zClosurez"),a=new B(a,C));b.href=a instanceof B&&a.constructor===B?a.g:"type_error:SafeUrl";b.click()};function S(){}u(S,M);S.prototype.g=function(){this.h({command:"failedToLoadRichContent"})};S.prototype.h=function(a){window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers.balloonCommand&&window.webkit.messageHandlers.balloonCommand.postMessage(a)};
function T(){}u(T,M);T.prototype.g=function(){console.error("No Earth integration on this platform, cannot perform action.")};var U=new O;document.body&&window.setTimeout(function(){var a=document.querySelector("div[unresolved]");a&&(a.classList.remove("hidden"),U.g())},1E3);
